export const DEFAULT_ABOUT_SECTION_ID = "DEFAULT_ABOUT_SECTION_ID";
export const DEFAULT_SERVICES_SECTION_ID = "DEFAULT_SERVICES_SECTION_ID";
export const DEFAULT_PORTFOLIO_SECTION_ID = "DEFAULT_PORTFOLIO_SECTION_ID";
export const DEFAULT_RESUME_SECTION_ID = "DEFAULT_RESUME_SECTION_ID";
export const DEFAULT_CONTACTS_SECTION_ID = "DEFAULT_CONTACTS_SECTION_ID";
